version: "3.9"

services:
  django:
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
#    image: sms-panel
    build:
      dockerfile: ./docker/local.Dockerfile
      context: .
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .compose/.compose.env
    depends_on:
      - postgres
      - redis
      - jaeger
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: sms_panel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
##      - "14268:14268"
##      - "9411:9411"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
