# Generated by Django 4.2.4 on 2023-08-03 16:29

import django.core.validators
from django.db import migrations, models
import django_prometheus.models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cellphone', models.CharField(db_index=True, max_length=13, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^\\+989\\d{9}$'), code='invalid', message='Enter a valid cellphone')], verbose_name='cellphone')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('person_type', models.PositiveSmallIntegerField(choices=[(1, 'Real'), (2, 'Legal')], default=1, verbose_name='person type')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Deactivate'), (1, 'Activate')], default=0, verbose_name='status')),
                ('legal_data', models.JSONField(default=dict, verbose_name='authorization')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'db_table': 'users',
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('user'), models.Model),
        ),
    ]
