# Generated by Django 4.2.4 on 2023-08-16 16:44

from django.db import migrations

import apps.common.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apps_user', '0002_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='legal_data',
            field=apps.common.fields.JSONSchemaField(default=dict, verbose_name='authorization'),
        ),
    ]
