# Generated by Django 4.2.4 on 2023-08-18 17:47

import django.db.models.deletion
import django_prometheus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_user', '0003_alter_user_legal_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_type', models.PositiveSmallIntegerField(choices=[(1, 'Legal'), (2, 'Financial')])),
                ('data', models.JSONField(default=dict, verbose_name='data')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Created'), (1, 'Accepted'), (2, 'Rejected')], default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apps_user.user')),
            ],
            options={
                'verbose_name': 'احراز هویت',
                'verbose_name_plural': 'احراز هویت\u200cها',
                'db_table': 'authorize_requests',
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('authorize_request'), models.Model),
        ),
    ]
