# Generated by Django 4.2.4 on 2023-08-07 18:31

from django.db import migrations, models
import django.db.models.deletion
import django_prometheus.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notif_type', models.PositiveSmallIntegerField(choices=[(1, 'Sms'), (2, 'Pushnotification')])),
                ('data', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps_user.user')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلان\u200cها',
                'db_table': 'notification',
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('notification'), models.Model),
        ),
    ]
