# Generated by Django 4.2.4 on 2023-08-02 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Requested'), (1, 'Senttoprovider'), (2, 'Rejected'), (3, 'Accepted'), (4, 'Rejectedbyprovider')], default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications_user.user')),
            ],
            options={
                'verbose_name': 'سرشماره',
                'verbose_name_plural': 'سرشماره\u200cها',
                'db_table': 'numbers',
            },
        ),
    ]
