# Generated by Django 4.2.4 on 2023-08-18 17:47

import django_prometheus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_user', '0004_authorizerequest'),
        ('apps_sender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareSender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(db_index=True, max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'سرشماره مشترک',
                'verbose_name_plural': 'سرشماره\u200cهای مشترک',
                'db_table': 'share_numbers',
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('share_sender'), models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='sender',
            unique_together={('owner', 'number')},
        ),
        migrations.AddIndex(
            model_name='sender',
            index=models.Index(models.F('owner'), models.F('number'), name='idx_senders_owner_id_number'),
        ),
    ]
