# Generated by Django 4.2.4 on 2023-08-18 18:32

import django.db.models.deletion
import django_prometheus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_user', '0004_authorizerequest'),
        ('apps_sender', '0002_sharesender_alter_sender_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sender',
            name='status',
        ),
        migrations.AddField(
            model_name='sender',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sender',
            name='number',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='SenderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_type', models.PositiveSmallIntegerField(choices=[(1, 'Create'), (2, 'Upgrade')])),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Requested'), (1, 'Senttoprovider'), (2, 'Rejected'), (3, 'Accepted'), (4, 'Rejectedbyprovider')], default=0)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_sender.sender')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_user.user')),
            ],
            options={
                'verbose_name': 'تبدیل نوع',
                'verbose_name_plural': 'تبدیل نوع\u200cها',
                'db_table': 'senders_upgrade_requests',
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('sender_upgrade_request'), models.Model),
        ),
    ]
