# Generated by Django 4.2.4 on 2023-08-18 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_sender', '0003_remove_sender_status_sender_is_shared_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sender',
            name='number_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Promotional'), (2, 'Service')], default=1),
        ),
        migrations.AlterField(
            model_name='senderrequest',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps_sender.sender'),
        ),
    ]
