name: Django CI

on:
  push:
    branches: [ "*"]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python requirements
      uses: aabadie/action-install-python-requirements@v2.0.1
      with:
        requirements: requirements.txt
        update-pip:
    - name: Run Tests
      run: |
        make test
#    - name: Python Django Coverage GitHub Action
#      uses: dc740/django-coveragepy-github-action@0.9
#      with:
#        django-app: sms-panel
#        minimum-coverage: 70
